# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generators.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 702)
        MainWindow.setMinimumSize(QtCore.QSize(420, 0))
        MainWindow.setMaximumSize(QtCore.QSize(420, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generator_img = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_img.sizePolicy().hasHeightForWidth())
        self.generator_img.setSizePolicy(sizePolicy)
        self.generator_img.setMinimumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.generator_img.setFont(font)
        self.generator_img.setStyleSheet("background-image: url(:/generators_prefix/unnamed.jpg);")
        self.generator_img.setAlignment(QtCore.Qt.AlignCenter)
        self.generator_img.setObjectName("generator_img")
        self.verticalLayout.addWidget(self.generator_img)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel_add = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel_add.setObjectName("nameLabel_add")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel_add)
        self.nameLineEdit_add = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit_add.setObjectName("nameLineEdit_add")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_add)
        self.pminLabel = QtWidgets.QLabel(self.centralwidget)
        self.pminLabel.setObjectName("pminLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pminLabel)
        self.pminLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pminLineEdit.setObjectName("pminLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pminLineEdit)
        self.pmaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.pmaxLabel.setObjectName("pmaxLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pmaxLabel)
        self.pmaxLineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.pmaxLineEdit_2.setObjectName("pmaxLineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pmaxLineEdit_2)
        self.aLabel = QtWidgets.QLabel(self.centralwidget)
        self.aLabel.setObjectName("aLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.aLabel)
        self.aLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.aLineEdit.setObjectName("aLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.aLineEdit)
        self.bLabel = QtWidgets.QLabel(self.centralwidget)
        self.bLabel.setObjectName("bLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bLabel)
        self.bLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.bLineEdit.setObjectName("bLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bLineEdit)
        self.cLabel = QtWidgets.QLabel(self.centralwidget)
        self.cLabel.setObjectName("cLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cLineEdit.setObjectName("cLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cLineEdit)
        self.iDLineEditin = QtWidgets.QLineEdit(self.centralwidget)
        self.iDLineEditin.setObjectName("iDLineEditin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.iDLineEditin)
        self.iDLabelin = QtWidgets.QLabel(self.centralwidget)
        self.iDLabelin.setObjectName("iDLabelin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.iDLabelin)
        self.verticalLayout.addLayout(self.formLayout)
        self.addgen_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addgen_btn.sizePolicy().hasHeightForWidth())
        self.addgen_btn.setSizePolicy(sizePolicy)
        self.addgen_btn.setMinimumSize(QtCore.QSize(400, 30))
        self.addgen_btn.setObjectName("addgen_btn")
        self.verticalLayout.addWidget(self.addgen_btn)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setMinimumSize(QtCore.QSize(68, 0))
        self.idLabel.setObjectName("idLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.idLineEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.remgen_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remgen_btn.sizePolicy().hasHeightForWidth())
        self.remgen_btn.setSizePolicy(sizePolicy)
        self.remgen_btn.setMinimumSize(QtCore.QSize(400, 30))
        self.remgen_btn.setObjectName("remgen_btn")
        self.verticalLayout.addWidget(self.remgen_btn)
        self.disp_dat_btn = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.disp_dat_btn.setObjectName("disp_dat_btn")
        self.verticalLayout.addWidget(self.disp_dat_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generator_img.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00ff00;\">Generators</span></p></body></html>"))
        self.nameLabel_add.setText(_translate("MainWindow", "Name:"))
        self.pminLabel.setText(_translate("MainWindow", "P_min [MW] ="))
        self.pmaxLabel.setText(_translate("MainWindow", "P_max [MW] ="))
        self.aLabel.setText(_translate("MainWindow", "a [$ / h] ="))
        self.bLabel.setText(_translate("MainWindow", "b [$ / h] ="))
        self.cLabel.setText(_translate("MainWindow", "c [$ / h] ="))
        self.iDLabelin.setText(_translate("MainWindow", "ID:"))
        self.addgen_btn.setText(_translate("MainWindow", "Add Generator"))
        self.idLabel.setText(_translate("MainWindow", "ID: "))
        self.remgen_btn.setText(_translate("MainWindow", "Remove Generator"))
        self.disp_dat_btn.setText(_translate("MainWindow", "Display Database"))
import generators_img_rc
